### PR TITLE
Fix helm values cycle

### PR DESCRIPTION
**Pull request by mnitchev**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create

### CODE REVIEW

**Comment by fiunchinho** [comment]
@AverageMarcus you have more experience with Helm, your feedback would be good here.

**Review by fiunchinho — CHANGES_REQUESTED** [review]
changelog

**Review by AverageMarcus — APPROVED** [review]
I hate having to do this but not got a better solution. 😞

**Pull request merged**
