### PR TITLE
Add proxy subnet

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does / why we need it

Towards https://github.com/giantswarm/roadmap/issues/1218

### Checklist

- [X] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by fiunchinho** [comment]
Created a cluster using this branch, and configuring the proxy subnet. This is the end result

image

Disclaimer: In order for this to work, [these changes need to be deployed](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/724), which is currently the case on all our installations.

**Comment by alex-dabija** [comment]
Nice. Yes, it's the expected outcome.

**Pull request merged**
